version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 3001:3001
      - 3000:3000
    volumes:
      - .:/app:consistent
      - /app/node_modules
    command: npm run dev
  tests:
    build:
        context: .
    command: npm run test
