version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - 3001:3001
      - 3000:3000
    volumes:
      - .:/app:consistent
    command: browser-sync -f . -w -f index.html -f **.js -f **.css --no-open	
